### ISSUE TITLE
[FEAT] 뷰 사이 Flow 연결

### ISSUE THREAD

**Issue by YoonAh-dev** [SOPT-29th-Joint-Seminar-5/Remember-iOS#11]
## 💡 Issue

뷰들 사이의 Flow를 연결합니다.

## 📝  todo
- [x] 글쓰기 버튼을 누르면 modal
- [x] 등록 버튼을 누르면 dismiss 후, push
- [x] 글이 써있는 셀을 누르면 push
