### ISSUE TITLE
[FEAT] 커뮤니티 뷰 서버 연결

### ISSUE THREAD

**Issue by jane1choi** [SOPT-29th-Joint-Seminar-5/Remember-iOS#16]
## 💡 Issue

커뮤니티 뷰에 대한 서버 통신입니다.

## 📝  todo

- [x] 메인 뷰 광고 이미지 GET
- [x] 메인 뷰 카테고리 태그 GET
- [x] 메인 뷰 게시글 데이터 GET
