### ISSUE TITLE
[UI] 커뮤니티 뷰 UI 구성

### ISSUE THREAD

**Issue by jane1choi** [SOPT-29th-Joint-Seminar-5/Remember-iOS#4]
## 💡 Issue

커뮤니티 뷰의 UI를 구성합니다.
 
## 📝  todo

- [X] 상단 바 UI 구성
- [X] 게시글 리스트 UI 구성
- [X] 카테고리 셀 UI 구성
