### ISSUE TITLE
[FEAT] 게시글작성뷰 내부 버튼 액션 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [SOPT-29th-Joint-Seminar-5/Remember-iOS#5]
## 💡 Issue
게시글 작성뷰 내부에 있는 버튼들의 액션을 구현합니다.

## 📝  todo
- [x] 닉네임 설정 버튼 구현
- [x] 커뮤니티 선택 버튼 구현
- [x] TextView, TextField에 따른 등록 버튼 Enable 구현
