### ISSUE TITLE
[UI] 게시물 상세뷰 레이아웃 구성

### ISSUE THREAD

**Issue by YoonAh-dev** [SOPT-29th-Joint-Seminar-5/Remember-iOS#9]
## 💡 Issue

게시물 상세뷰에 대한 레이아웃을 구성합니다.

## 📝  todo
- [x] 상단 Navigation bar 설정
- [x] 게시물 상세뷰 TableView 구성
- [x] 상단 Xib 생성
- [x] 하단 Xib 생성
